### ISSUE TITLE
Product Entry Allows you to Submit Faulty Data

### ISSUE THREAD

**Issue by shazaman23** [jfarnworth/GroceryStoreApp#3]
![productadditionerrors](https://cloud.githubusercontent.com/assets/15066237/19096571/b5f7ec5c-8a5a-11e6-987a-91a56f71d28e.PNG)

If you type random junk into the different boxes, you can submit data that is invalid and it excepts it into the database. Specifically the price. It shouldn't let you submit a letter in it.

**Comment by shazaman23** [comment]
![priceerrors2](https://cloud.githubusercontent.com/assets/15066237/19096777/6fc89720-8a5c-11e6-9aca-29c70522742d.PNG)

**Comment by jfarnworth** [comment]
Addressed. Iteration 3 uses spinboxes instead of text fields, which means no more e. I really don't understand why the int validator let that through in the first place...
