### ISSUE TITLE
Price Page Doesn't Handle Invalid Data

### ISSUE THREAD

**Issue by shazaman23** [jfarnworth/GroceryStoreApp#4]
![priceerrors](https://cloud.githubusercontent.com/assets/15066237/19096714/c0291a7e-8a5b-11e6-88c8-68b844de1604.PNG)

With the invalid data that I entered with the product, it doesn't know what to do with the price that has invalid data. No error message is displayed, items won't add to a receipt, etc.

**Comment by jfarnworth** [comment]
As with other submitted bugs, I can't replicate this one. The price field has a double validator set so it won't allow non number characters. I can get the E to type, but it won't update the database unless a valid price has been set, so once again, I can't replicate your bug.

**Comment by jfarnworth** [comment]
Ok, so this was caused by the double validator allowing the character 'e' for whatever reason. I've addressed this by making the input a double spinbox that will no longer allow characters of any kind. Fixed.
