### ISSUE TITLE
Normal Price Input Doesn't Submit

### ISSUE THREAD

**Issue by shazaman23** [jfarnworth/GroceryStoreApp#6]
![typicalwontwork](https://cloud.githubusercontent.com/assets/15066237/19096802/b2720a70-8a5c-11e6-95cf-39d8077fff0e.PNG)

This should either work or be denied when the product is entered

**Comment by jfarnworth** [comment]
I notice that there's a comma in the price per unit and I don't understand how that's possible. When I try to replicate this error the database won't accept a comma in the price and I can't replicate the way your screen is set up and I can't replicate this issue.

**Comment by jfarnworth** [comment]
Fixed with double spinbox input.
