### ISSUE TITLE
Multiple Submissions Don't Combine

### ISSUE THREAD

**Issue by shazaman23** [jfarnworth/GroceryStoreApp#7]
![multiplesubmissions](https://cloud.githubusercontent.com/assets/15066237/19096830/f543606a-8a5c-11e6-83c3-424a70addc61.PNG)

With multiple submissions of the same item (at least that all have the same ID) the receipt should consolidate entries

**Comment by jfarnworth** [comment]
This is definitely a lack of functionality, but I don't know that I'd call it a bug. It certainly wasn't functionality covered in the software specification.
