### ISSUE TITLE
Remove Items Doesn't Work

### ISSUE THREAD

**Issue by shazaman23** [jfarnworth/GroceryStoreApp#8]
![removenope](https://cloud.githubusercontent.com/assets/15066237/19096881/5f3460aa-8a5d-11e6-96cb-5320a06dd0c1.PNG)

With the following entries, no matter what item is selected it won't delete the item. In this example I clicked the item circled in red on the right and then I clicked the "Remove Item" button on the left and nothing happened. I repeated the test for all of the entries and nothing would remove.

**Comment by shazaman23** [comment]
Just to clarify on this, I am logged in as an admin with admin privileges.

**Comment by jfarnworth** [comment]
I wasn't able to replicate this error, so I'm not sure how to proceed...

**Comment by phong1990** [comment]
Can you guys please finalize this error? You may work together to come to a conclusion and it's fine. I just need to know if we can count this as an error or not.
-Leonard-

**Comment by shazaman23** [comment]
I've replicated the error again. I can show you after class if you'd like.

**Comment by jfarnworth** [comment]
it's been taken care of. Fixed.
