### ISSUE TITLE
Program Allows You To Set All Non-Admin

### ISSUE THREAD

**Issue by shazaman23** [jfarnworth/GroceryStoreApp#9]
![cash3](https://cloud.githubusercontent.com/assets/15066237/19096964/1f46c8ce-8a5e-11e6-99cd-630cd057742d.PNG)
![cash4](https://cloud.githubusercontent.com/assets/15066237/19096965/1f476c3e-8a5e-11e6-8875-405f84d8726a.PNG)
![cash5](https://cloud.githubusercontent.com/assets/15066237/19096962/1f448618-8a5e-11e6-85b0-fe21304bc2b0.PNG)
![cash1](https://cloud.githubusercontent.com/assets/15066237/19096961/1f41e1f6-8a5e-11e6-990b-b10ec8ad99a3.PNG)
![cash2](https://cloud.githubusercontent.com/assets/15066237/19096963/1f4586a8-8a5e-11e6-88ec-0ab1065e5a3b.PNG)

I just set all of the users, including the original admin to Cashier and they all updated that way. If I log out, I will have broken the program forever. No one can log in as an admin.

**Comment by jfarnworth** [comment]
Totally legit. The Admin can no longer be set to a Cashier in Iteration 2.

**Comment by shazaman23** [comment]
Hey, at least I found one bug that was legit, right?
